apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-pipeline
  name: server-airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      name: server-airflow
  template:
    metadata:
      namespace: ml-pipeline
      labels:
        name: server-airflow
    spec:
      containers:
        - name: server-airflow
          image: tavishi8178502223/abc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: rest
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "4Gi"
              cpu: "2"
           
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

apiVersion: v1
kind: Service
metadata:
  namespace: ml-pipeline
  name: server-airflow
spec:
  selector:
    name: server-airflow
  ports:
    - port: 80
      targetPort: rest
  type: LoadBalancer
