apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: server
  name: ml-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ml-pipeline
  template:
    metadata:
      namespace: ml-pipeline
      labels:
        name: ml-pipeline
    spec:
      containers:
        - name: ml-pipeline
          image: "tavishi1402/sap_project:latest"
          imagePullPolicy: Always
          command: 
            - "bash"
            - "-c"
            - "uvicorn appfast:app --host 0.0.0.0 --port 8000 --workers 2"
          ports:
            - containerPort: 8000
              name: rest
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "2Gi"
              cpu: "1"
      imagePullSecrets:
        - name: azure-secret
---

apiVersion: v1
kind: Service
metadata:
  namespace: ml-pipeline
  name: ml-pipeline
  
spec:
  selector:
    name: ml-pipeline
  ports:
    - port: 80
      targetPort: rest
  type: LoadBalancer