apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: staging
  name: ml-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ml-pipeline
  template:
    metadata:
      labels:
        name: ml-pipeline
    spec:
      containers:
        - name: ml-pipeline
          image: "tavishi1402/sap_project:latest"
          imagePullPolicy: Always
          command: 
            - "bash"
            - "-c"
            - "flask run --host=0.0.0.0 --port=8000"
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "2Gi"
              cpu: "1"
      imagePullSecrets:
        - name: gcp-secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: ml-pipeline
spec:
  selector:
    app: ml-pipeline
  ports:
    - port: 80
      targetPort: http
  type: LoadBalancer
