name: Build and Push to GKE verba backend

on:
  push:
    branches:
      - main


jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: tavishi1402
        password: dckr_pat_eRvjeIa_sPytCNUJ-AZTE2_CtzY

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: tavishi1402/abc:latest
      
      
  continuous_deployment:
    name: continuous delivery to GKE cluster
    runs-on: ubuntu-latest
    needs: push_to_registry
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'tavishi-sap-cluster-1'
          location: 'us-central1-c'

      - name: "install kubernetes"
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Deploy
        run: |
          kubectl apply -f k8s/manifest.yml -n ml-pipeline
